name: build
on: push
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        arch: [ x86_64, arm64 ]
    name: build on ${{ matrix.arch }}
    runs-on: ${{ matrix.arch == 'arm64' && 'ubuntu-24.04-arm' || 'ubuntu-24.04' }}
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup devcontainer
        run: podman build -t dev .devcontainer
      - name: build
        run: podman run --rm --read-only -v "$PWD:/workspace" -w /workspace dev make
